# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessWindow(object):
    def setupUi(self, mainWindow):
            
        mainWindow.setObjectName("ProcessWindow")
        mainWindow.resize(500, 150)
        mainWindow.setMinimumSize(QtCore.QSize(500, 150))
        mainWindow.setMaximumSize(QtCore.QSize(500, 150))
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 150))
        self.frame.setStyleSheet("background-color: #ffffff;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(20, 40, 400, 25))
        self.title.setStyleSheet("color: #020202;\n"         
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: 0px;")
        self.title.setObjectName("title")
        self.title.setText("??곗댄몃? 吏?以????.. ??留 湲곕ㅻ?二쇱몄...")
        
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(10, 100, 480, 20))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"    border: solid grey;\n"
"    border-radius: 10px;\n"
"    background-color: #bfbfbf;\n"
"    color: black;\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x5:0, y1:0, x5:0, y2:0, stop:0 #020202, stop:1 #020202);\n"
"/*\n"
"    background-color: #ffffff;\n"
"*/\n"
"    border-radius :10px;\n"
"}   ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        
        mainWindow.setCentralWidget(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

