# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, window):
            
        window.setObjectName("MainWindow")
        window.resize(700, 500)
        window.setMinimumSize(QtCore.QSize(900, 900))
        window.setMaximumSize(QtCore.QSize(900, 900))
        window.setUnifiedTitleAndToolBarOnMac(False)
        
        self.mainwidget = QtWidgets.QWidget(window)
        self.mainwidget.setObjectName("centralwidget")
        
        self.frame = QtWidgets.QFrame(self.mainwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 900, 900))
        self.frame.setStyleSheet("background-color: #FAFAFA;")
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.top_frame = QtWidgets.QFrame(self.frame)
        self.top_frame.setGeometry(QtCore.QRect(2, 2, 896, 48))
        self.top_frame.setStyleSheet("background-color: #ffffff;")
        self.top_frame.setObjectName("top_frame")

        self.logoButton = QtWidgets.QPushButton(self.top_frame)
        self.logoButton.setGeometry(QtCore.QRect(10, 11, 25, 25))
        self.logoButton.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #ffffff;\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5E616A;\n"
"}")
        logo = QtGui.QIcon()
        logo.addPixmap(QtGui.QPixmap("resource/trayIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.logoButton.setIcon(logo)
        self.logoButton.setIconSize(QtCore.QSize(25, 25))
        self.logoButton.setObjectName("logoButton")
        
        self.program_title = QtWidgets.QLabel(self.top_frame)
        self.program_title.setGeometry(QtCore.QRect(40, 8, 500, 30))
        self.program_title.setStyleSheet("color: #020202;\n"
                                         
"background-color: #ffffff;\n"
"font-size: 11pt;\n"
"font-weight: bold;\n"
"border: 0px;")
        self.program_title.setObjectName("program_title")
        self.program_title.setText("블로그 서로이웃 추적 시스템 - Naver Neighbour Check")
     
        self.minimumButton = QtWidgets.QPushButton(self.top_frame)
        self.minimumButton.setGeometry(QtCore.QRect(830, 15, 20, 20))
        self.minimumButton.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #020202;\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5E616A;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/Minimize_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.minimumButton.setIcon(icon1)
        self.minimumButton.setIconSize(QtCore.QSize(13, 13))
        self.minimumButton.setObjectName("minimumButton")
        
        self.exitButton = QtWidgets.QPushButton(self.top_frame)
        self.exitButton.setGeometry(QtCore.QRect(860, 15, 20, 20))
        self.exitButton.setStyleSheet("QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #020202;\n"
"    border: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5E616A;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resource/close_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exitButton.setIcon(icon2)
        self.exitButton.setIconSize(QtCore.QSize(13, 13))
        self.exitButton.setObjectName("exitButton")

        self.id_title = QtWidgets.QLabel(self.frame)
        self.id_title.setGeometry(QtCore.QRect(20, 100, 80, 30))
        self.id_title.setStyleSheet("color: #020202;\n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: 0px;")
        self.id_title.setObjectName("searchText_title")
        self.id_title.setAlignment(QtCore.Qt.AlignCenter)
        self.id_title.setText("아이디")
       
        self.idFrame = QtWidgets.QFrame(self.frame)
        self.idFrame.setGeometry(QtCore.QRect(110, 90, 200, 50))
        self.idFrame.setStyleSheet("background-color:  #ffffff;\n"
"border: 1px solid  #020202;\n"
"border-bottom-left-radius:3px;\n"
"border-top-left-radius: 3;\n"
"border-bottom-right-radius: 3px;\n"
"border-top-right-radius: 3px;")
        self.idFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.idFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.idFrame.setObjectName("searchTextFrame")
        self.idEdit = QtWidgets.QLineEdit(self.idFrame)
        self.idEdit.setGeometry(QtCore.QRect(10, 5, 180, 40))
        self.idEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.idEdit.setStyleSheet("background-color:  #ffffff;\n"
                                       
"font-size: 12pt;\n"
"color: #020202;\n"
"border: 0px;")
        self.idEdit.setObjectName("searchTextEdit")
        
        
        self.pw_title = QtWidgets.QLabel(self.frame)
        self.pw_title.setGeometry(QtCore.QRect(330, 100, 90, 30))
        self.pw_title.setStyleSheet("color: #020202;\n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: 0px;")
        self.pw_title.setObjectName("fitKeyword_title")
        self.pw_title.setAlignment(QtCore.Qt.AlignCenter)
        self.pw_title.setText("비밀번호")
        
        self.pwFrame = QtWidgets.QFrame(self.frame)
        self.pwFrame.setGeometry(QtCore.QRect(420, 90, 200, 50))
        self.pwFrame.setStyleSheet("background-color:  #ffffff;\n"
"border: 1px solid  #020202;\n"
"border-bottom-left-radius:3px;\n"
"border-top-left-radius: 3;\n"
"border-bottom-right-radius: 3px;\n"
"border-top-right-radius: 3px;")
        self.pwFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pwFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pwFrame.setObjectName("fitKeywordFrame")
        self.pwEdit = QtWidgets.QLineEdit(self.pwFrame)
        self.pwEdit.setGeometry(QtCore.QRect(10, 5, 150, 38))
        self.pwEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.pwEdit.setStyleSheet("background-color:  #ffffff;\n"
                                       
"font-size: 12pt;\n"
"color: #020202;\n"
"border: 0px;")
        self.pwEdit.setObjectName("fitKeywordEdit")
        self.pwEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        
        self.btnSearchFollower = QtWidgets.QPushButton(self.frame)
        self.btnSearchFollower.setGeometry(QtCore.QRect(680, 90, 200, 50))
        self.btnSearchFollower.setMinimumSize(QtCore.QSize(200, 50))
        self.btnSearchFollower.setMaximumSize(QtCore.QSize(200, 50))
        self.btnSearchFollower.setStyleSheet("QPushButton {\n"
"image: url(resource/btnFindFriend.png);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"image: url(resource/btnFindFriendHover.png);\n"
"    \n"
"}"
)
        self.btnSearchFollower.setObjectName("btnSearchKeword")
        
        self.btnStop = QtWidgets.QPushButton(self.frame)
        self.btnStop.setGeometry(QtCore.QRect(680, 90, 200, 50))
        self.btnStop.setMinimumSize(QtCore.QSize(200, 50))
        self.btnStop.setMaximumSize(QtCore.QSize(200, 50))
        self.btnStop.setStyleSheet("QPushButton {\n"
"image: url(resource/btnStop.png);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"image: url(resource/btnStopHover.png);\n"
"    \n"
"}"
)
        self.btnStop.setObjectName("btnSearchKeword")
        self.btnStop.hide()

        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(20, 175, 860, 20))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"    border: solid grey;\n"
"    border-radius: 10px;\n"
"    background-color: #bfbfbf;\n"
"    color: black;\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x5:0, y1:0, x5:0, y2:0, stop:0 #020202, stop:1 #020202);\n"
"/*\n"
"    background-color: #ffffff;\n"
"*/\n"
"    border-radius :10px;\n"
"}   ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        
        self.currentFriendName = QtWidgets.QLabel(self.frame)
        self.currentFriendName.setGeometry(QtCore.QRect(20, 213, 860, 30))
        self.currentFriendName.setStyleSheet("color: #020202;\n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: 0px;")
        self.currentFriendName.setObjectName("searchText_title")
        self.currentFriendName.setAlignment(QtCore.Qt.AlignCenter)
        self.currentFriendName.setText("")

        self.result_title = QtWidgets.QLabel(self.frame)
        self.result_title.setGeometry(QtCore.QRect(580, 235, 300, 30))
        self.result_title.setStyleSheet("color: #020202;\n"
"font-size: 12pt;\n"
"font-weight: bold;\n"
"border: 0px;")
        self.result_title.setObjectName("fitKeyword_title")
        self.result_title.setAlignment(QtCore.Qt.AlignRight)
        self.result_title.setText("")
        
        self.table = QtWidgets.QTableWidget(self.frame)
        self.table.setGeometry(QtCore.QRect(20, 270, 860, 550))
        self.table.setObjectName("tableWidget")
        self.table.setColumnCount(6)
        self.table.setHorizontalHeaderLabels(['그룹명', '상태', '이웃명', '최근글', '이웃추가일', '삭제'])
        self.table.horizontalHeader().setFixedHeight(40)
        # self.table.verticalHeader().setVisible(False)
        self.table.setRowHeight(0, 40)
        self.table.setRowHeight(1, 40)
        self.table.setRowHeight(2, 40) 
        self.table.setRowHeight(3, 40) 
        self.table.setRowHeight(4, 40)
        self.table.setRowHeight(5, 58)
        self.table.setColumnWidth(0, 100)
        self.table.setColumnWidth(1, 100)
        self.table.setColumnWidth(2, 400) 
        self.table.setColumnWidth(3, 100) 
        self.table.setColumnWidth(4, 100)
        self.table.setColumnWidth(5, 58)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
       
        self.btnAllDelete = QtWidgets.QPushButton(self.frame)
        self.btnAllDelete.setGeometry(QtCore.QRect(730, 835, 150, 50))
        self.btnAllDelete.setMinimumSize(QtCore.QSize(150, 50))
        self.btnAllDelete.setMaximumSize(QtCore.QSize(150, 50))
        self.btnAllDelete.setStyleSheet("QPushButton {\n"
"image: url(resource/btnDelete.png);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"image: url(resource/btnDeleteHover.png);\n"
"    \n"
"}"
)
        self.btnAllDelete.setObjectName("btnAllDelete")
        self.btnAllDelete.hide()
        
        window.setCentralWidget(self.mainwidget)
        QtCore.QMetaObject.connectSlotsByName(window)